# Test that Terraform code is able to build a plan with GitHub Actions
# Version 1.1
name: 'Terraform-Build-Test'

on:
   push:
     branches: [ "main" ]
   pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform-Build-Test'
    runs-on: ubuntu-latest
    environment: build-test
    defaults:
      run:
        shell: bash
        working-directory: ./.github/workflows/

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform FMT Check
      working-directory: ./
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
